"""Shared enums, constants and compatibility aliases."""

from __future__ import annotations

from enum import Enum, IntEnum

INHERIT_VALUE = -100
MEDIA_CACHE_TTL_SECONDS_DEFAULT = 15 * 60
MEDIA_CACHE_TTL_SECONDS_MIN = 60


class UserState(IntEnum):
    BANNED = -1
    USER = 1


class SendMode(IntEnum):
    LINK_ONLY = -1
    AUTO = 0
    DIRECT = 1


class DisplayToggle(IntEnum):
    DISABLED = -1
    AUTO = 0
    FORCED = 1


class DisplayVia(IntEnum):
    FULLY_DISABLED = -2
    LINK_ONLY = -1
    AUTO = 0
    FORCED = 1


class PlatformName(str, Enum):
    TELEGRAM = "telegram"
    ONEBOT = "aiocqhttp"
    QQ_OFFICIAL = "qq_official"
    WEIXIN_OC = "weixin_oc"
    LARK = "lark"


class PlatformAlias(str, Enum):
    TELEGRAM_SHORT = "tg"
    ONEBOT = "onebot"
    ONEBOT11 = "onebot11"
    ONEBOTV11 = "onebotv11"
    QQOFFICIAL = "qqofficial"
    QQ = "qq"
    WECHAT = "wechat"
    WEIXIN = "weixin"


class PlatformStrategyTemplate(str, Enum):
    TELEGRAM = "telegram_strategy"
    ONEBOT = "onebot_strategy"
    QQ_OFFICIAL = "qq_official_strategy"


USER_STATE_BANNED = int(UserState.BANNED)
USER_STATE_USER = int(UserState.USER)

SEND_MODE_LINK_ONLY = int(SendMode.LINK_ONLY)
SEND_MODE_AUTO = int(SendMode.AUTO)
SEND_MODE_DIRECT = int(SendMode.DIRECT)

DISPLAY_DISABLED = int(DisplayToggle.DISABLED)
DISPLAY_AUTO = int(DisplayToggle.AUTO)
DISPLAY_FORCED = int(DisplayToggle.FORCED)

DISPLAY_VIA_FULLY_DISABLED = int(DisplayVia.FULLY_DISABLED)
DISPLAY_VIA_LINK_ONLY = int(DisplayVia.LINK_ONLY)
DISPLAY_VIA_AUTO = int(DisplayVia.AUTO)
DISPLAY_VIA_FORCED = int(DisplayVia.FORCED)

PLATFORM_TELEGRAM = PlatformName.TELEGRAM.value
PLATFORM_ONEBOT = PlatformName.ONEBOT.value
PLATFORM_ONEBOT_ALIASES = (
    PlatformAlias.ONEBOT.value,
    PlatformAlias.ONEBOT11.value,
    PlatformAlias.ONEBOTV11.value,
)
PLATFORM_QQ_OFFICIAL = PlatformName.QQ_OFFICIAL.value
PLATFORM_QQ_OFFICIAL_ALIASES = (
    PlatformAlias.QQOFFICIAL.value,
    PlatformAlias.QQ.value,
)
PLATFORM_WEIXIN_OC = PlatformName.WEIXIN_OC.value
PLATFORM_WEIXIN_ALIASES = (
    PlatformAlias.WECHAT.value,
    PlatformAlias.WEIXIN.value,
)

TELEGRAM_PHOTO_MAX_BYTES = 10 * 1024 * 1024
TELEGRAM_ANIMATION_MAX_BYTES = 50 * 1024 * 1024
TELEGRAM_VIDEO_MAX_BYTES = 50 * 1024 * 1024
TELEGRAM_DOCUMENT_MAX_BYTES = 50 * 1024 * 1024

ONEBOT_NAPCAT_STREAM_MODE_DEFAULT = "fallback"
ONEBOT_VIDEO_MAX_BYTES = 100 * 1024 * 1024

QQ_OFFICIAL_MEDIA_THRESHOLD_DEFAULT = 0
QQ_OFFICIAL_IMAGE_MAX_BYTES = 10 * 1024 * 1024
QQ_OFFICIAL_GIF_MAX_BYTES = 10 * 1024 * 1024
QQ_OFFICIAL_VIDEO_MAX_BYTES = 12 * 1024 * 1024
QQ_OFFICIAL_FILE_MAX_BYTES = 12 * 1024 * 1024
QQ_OFFICIAL_DEGRADE_STRATEGY_LINK_ONLY = "link_only"
QQ_OFFICIAL_DEGRADE_STRATEGY_FILE_THEN_LINK = "file_then_link"
QQ_OFFICIAL_DEGRADE_STRATEGY_FAIL = "fail"
QQ_OFFICIAL_DEGRADE_STRATEGY_DEFAULT = QQ_OFFICIAL_DEGRADE_STRATEGY_FILE_THEN_LINK
QQ_OFFICIAL_DEGRADE_STRATEGY_OPTIONS = (
    QQ_OFFICIAL_DEGRADE_STRATEGY_LINK_ONLY,
    QQ_OFFICIAL_DEGRADE_STRATEGY_FILE_THEN_LINK,
    QQ_OFFICIAL_DEGRADE_STRATEGY_FAIL,
)
QQ_OFFICIAL_MARKDOWN_MODE_AUTO = "auto"
QQ_OFFICIAL_MARKDOWN_MODE_FORCE = "force"
QQ_OFFICIAL_MARKDOWN_MODE_PLAIN = "plain"
QQ_OFFICIAL_MARKDOWN_MODE_DEFAULT = QQ_OFFICIAL_MARKDOWN_MODE_AUTO
QQ_OFFICIAL_MARKDOWN_MODE_OPTIONS = (
    QQ_OFFICIAL_MARKDOWN_MODE_AUTO,
    QQ_OFFICIAL_MARKDOWN_MODE_FORCE,
    QQ_OFFICIAL_MARKDOWN_MODE_PLAIN,
)

SENDER_STRATEGY_ENABLED_PLATFORMS = (
    PlatformName.TELEGRAM.value,
    PlatformName.ONEBOT.value,
    PlatformName.QQ_OFFICIAL.value,
)

PLATFORM_STRATEGY_TEMPLATE_KEYS: dict[str, str] = {
    PlatformName.TELEGRAM.value: PlatformStrategyTemplate.TELEGRAM.value,
    PlatformName.ONEBOT.value: PlatformStrategyTemplate.ONEBOT.value,
    PlatformName.QQ_OFFICIAL.value: PlatformStrategyTemplate.QQ_OFFICIAL.value,
}

PLATFORM_ALIASES: dict[str, tuple[str, ...]] = {
    PlatformName.TELEGRAM.value: (PlatformAlias.TELEGRAM_SHORT.value,),
    PlatformName.ONEBOT.value: PLATFORM_ONEBOT_ALIASES,
    PlatformName.QQ_OFFICIAL.value: PLATFORM_QQ_OFFICIAL_ALIASES,
    PlatformName.WEIXIN_OC.value: PLATFORM_WEIXIN_ALIASES,
    PlatformName.LARK.value: ("feishu", "larksuite"),
}

ONEBOT_PLATFORMS = {PlatformName.ONEBOT.value, *PLATFORM_ONEBOT_ALIASES}
TELEGRAM_PLATFORMS = {
    PlatformName.TELEGRAM.value,
    PlatformAlias.TELEGRAM_SHORT.value,
}
QQ_OFFICIAL_PLATFORMS = {
    PlatformName.QQ_OFFICIAL.value,
    *PLATFORM_QQ_OFFICIAL_ALIASES,
}
WEIXIN_PLATFORMS = {PlatformName.WEIXIN_OC.value, *PLATFORM_WEIXIN_ALIASES}

WEIXIN_IMAGE_MAX_BYTES = 10 * 1024 * 1024
WEIXIN_GIF_MAX_BYTES = 5 * 1024 * 1024
WEIXIN_VIDEO_MAX_BYTES = 10 * 1024 * 1024
WEIXIN_FILE_MAX_BYTES = 20 * 1024 * 1024

GIF_COMPRESS_TARGET_MAX_BYTES = min(
    QQ_OFFICIAL_GIF_MAX_BYTES,
    WEIXIN_GIF_MAX_BYTES,
    TELEGRAM_ANIMATION_MAX_BYTES,
)

# GIF 转码档位。compatibility 面向内存受限容器，避免高分辨率视频在 palette
# 滤镜阶段耗尽进程内存；quality 保留历史的原始质量行为供用户显式选择。
GIF_TRANSCODE_PROFILE_COMPATIBILITY = "compatibility"
GIF_TRANSCODE_PROFILE_BALANCED = "balanced"
GIF_TRANSCODE_PROFILE_QUALITY = "quality"
GIF_TRANSCODE_PROFILE_OPTIONS = (
    GIF_TRANSCODE_PROFILE_COMPATIBILITY,
    GIF_TRANSCODE_PROFILE_BALANCED,
    GIF_TRANSCODE_PROFILE_QUALITY,
)
